/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import style.RoundedPanel;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author rasmx
 */
public class ViewInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesionView1
     */
    public ViewInicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Inicio Sesion");
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_contenedorInicio = new RoundedPanel(60, Color.WHITE);
        lbl_inicioSesion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cmbx_tipoUsuario = new javax.swing.JComboBox<>();
        lbl_LogIn = new javax.swing.JLabel();
        icon_logo = new javax.swing.JLabel();
        icon_mail = new javax.swing.JLabel();
        icon_pass = new javax.swing.JLabel();
        icon_tipoUser = new javax.swing.JLabel();
        fld_username = new javax.swing.JTextField();
        lbl_questionPass = new javax.swing.JLabel();
        fld_password = new javax.swing.JTextField();
        fondo_inicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_contenedorInicio.setBackground(new java.awt.Color(0, 0, 0));
        pnl_contenedorInicio.setPreferredSize(new java.awt.Dimension(1080, 600));

        lbl_inicioSesion.setFont(new java.awt.Font("Sitka Banner", 0, 36)); // NOI18N
        lbl_inicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_inicioSesion.setText("INICIO DE SESION");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        cmbx_tipoUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        cmbx_tipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "EMPLEADO" }));
        cmbx_tipoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbx_tipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_tipoUsuarioActionPerformed(evt);
            }
        });

        lbl_LogIn.setBackground(new java.awt.Color(255, 255, 255));
        lbl_LogIn.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_LogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LogIn.setText("LOG IN");
        lbl_LogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_LogIn.setOpaque(true);
        lbl_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LogInMouseClicked(evt);
            }
        });

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icon_log_in/Logo.png"))); // NOI18N

        icon_mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icon_log_in/icon-mail.png"))); // NOI18N

        icon_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icon_log_in/icon-pass.png"))); // NOI18N

        icon_tipoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icon_log_in/icon-rol.png"))); // NOI18N

        fld_username.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        fld_username.setBorder(null);

        lbl_questionPass.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_questionPass.setText("¿Has olvidado tu contraseña?");

        fld_password.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        fld_password.setBorder(null);

        javax.swing.GroupLayout pnl_contenedorInicioLayout = new javax.swing.GroupLayout(pnl_contenedorInicio);
        pnl_contenedorInicio.setLayout(pnl_contenedorInicioLayout);
        pnl_contenedorInicioLayout.setHorizontalGroup(
            pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_contenedorInicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_inicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_contenedorInicioLayout.createSequentialGroup()
                        .addGroup(pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(icon_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fld_password, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_contenedorInicioLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(icon_mail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fld_username, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(icon_tipoUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbx_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(45, 45, 45))))
            .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                .addGroup(pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(icon_logo))
                    .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lbl_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lbl_questionPass)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_contenedorInicioLayout.setVerticalGroup(
            pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_logo)
                .addGap(37, 37, 37)
                .addGroup(pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                        .addComponent(fld_password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_contenedorInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbx_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_contenedorInicioLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(icon_tipoUser)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(lbl_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lbl_questionPass)
                        .addGap(31, 31, 31))
                    .addGroup(pnl_contenedorInicioLayout.createSequentialGroup()
                        .addComponent(icon_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(pnl_contenedorInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 360, 640));

        fondo_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icon_log_in/InicioDeSesion-img.jpg"))); // NOI18N
        getContentPane().add(fondo_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbx_tipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_tipoUsuarioActionPerformed

    }//GEN-LAST:event_cmbx_tipoUsuarioActionPerformed

    private void lbl_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LogInMouseClicked
        ViewMenuPrincipal menu = new ViewMenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_LogInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception e) {
            e.printStackTrace();

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbx_tipoUsuario;
    private javax.swing.JTextField fld_password;
    private javax.swing.JTextField fld_username;
    private javax.swing.JLabel fondo_inicio;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel icon_mail;
    private javax.swing.JLabel icon_pass;
    private javax.swing.JLabel icon_tipoUser;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_LogIn;
    private javax.swing.JLabel lbl_inicioSesion;
    private javax.swing.JLabel lbl_questionPass;
    private static javax.swing.JPanel pnl_contenedorInicio;
    // End of variables declaration//GEN-END:variables
}
