package view;

import style.RoundedPanel;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Panel de registro de Registro de entradas en la interfaz gráfica de la
 * aplicación.
 * <p>
 * Esta clase define el panel para la vista de registro de entradas, con un
 * fondo personalizado.
 * </p>
 *
 * @author Ralfph
 */
public class ViewRegistroEntradas extends javax.swing.JPanel {

    /**
     * Constructor que inicializa el panel de registro de entradas y establece
     * el color de fondo.
     */
    public ViewRegistroEntradas() {
        this.setBackground(Color.decode("#000511"));
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cont_icon_user1 =  new RoundedPanel(60, new Color(19, 22, 27));
        jLabel10 = new javax.swing.JLabel();
        panel_cont_icon_user2 =  new RoundedPanel(30, new Color(19, 22, 27));
        panel_cont_icon_user3 =  new RoundedPanel(30, Color.WHITE);
        lbl_id_entrada = new javax.swing.JLabel();
        txtIdEntrada = new javax.swing.JTextField();
        lbl_nombreProducto = new javax.swing.JLabel();
        lbl_stock = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_precioEntrada = new javax.swing.JLabel();
        lbl_precioVenta = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        txtTotalE = new javax.swing.JTextField();
        txtFechaEntrada = new javax.swing.JTextField();
        txtDescOperacion = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtCantidadP = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panel_cont_icon_user5 =  new RoundedPanel(30, Color.WHITE);
        lbl_buscarP = new javax.swing.JLabel();
        lbl_idProducto_1 = new javax.swing.JLabel();
        txtBuscarNameProduct = new javax.swing.JTextField();
        panel_cont_icon_user7 =  new RoundedPanel(60, new Color(0,5,17));
        jLabel11 = new javax.swing.JLabel();
        panel_cont_icon_user8 =  new RoundedPanel(60, new Color(0,5,17));
        btnRegistrarEntrada = new javax.swing.JButton();
        panel_cont_icon_user6 =  new RoundedPanel(60, new Color(0, 5, 17));
        btnEditarEntrada = new javax.swing.JButton();
        btnEliminarEntrada = new javax.swing.JButton();
        panel_cont_icon_user10 =  new RoundedPanel(30, Color.WHITE);
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntradas = new javax.swing.JTable();
        panel_cont_icon_user11 =  new RoundedPanel(30, Color.WHITE);
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaProductosABuscarEnt = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(839, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cont_icon_user1.setForeground(new java.awt.Color(19, 22, 27));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registro de Entradas");

        javax.swing.GroupLayout panel_cont_icon_user1Layout = new javax.swing.GroupLayout(panel_cont_icon_user1);
        panel_cont_icon_user1.setLayout(panel_cont_icon_user1Layout);
        panel_cont_icon_user1Layout.setHorizontalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel_cont_icon_user1Layout.setVerticalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panel_cont_icon_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1100, 60));

        panel_cont_icon_user2.setForeground(new java.awt.Color(19, 22, 27));

        panel_cont_icon_user3.setForeground(new java.awt.Color(19, 22, 27));

        lbl_id_entrada.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_id_entrada.setText("ID Entrada");

        txtIdEntrada.setEditable(false);
        txtIdEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEntradaActionPerformed(evt);
            }
        });

        lbl_nombreProducto.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_nombreProducto.setText("Nombre Producto");

        lbl_stock.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_stock.setText("Descripcion de Operacion:");

        lbl_fecha.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_fecha.setText("Fecha:");

        lbl_precioEntrada.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_precioEntrada.setText("Cantidad:");

        lbl_precioVenta.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_precioVenta.setText("Precio Unitario:");

        lbl_total.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_total.setText("Total:");

        txtTotalE.setEditable(false);

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });

        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod Producto");

        javax.swing.GroupLayout panel_cont_icon_user3Layout = new javax.swing.GroupLayout(panel_cont_icon_user3);
        panel_cont_icon_user3.setLayout(panel_cont_icon_user3Layout);
        panel_cont_icon_user3Layout.setHorizontalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(txtTotalE, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidadP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_precioVenta)
                                    .addComponent(lbl_precioEntrada)
                                    .addComponent(lbl_fecha)
                                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(lbl_stock)
                    .addComponent(lbl_id_entrada)
                    .addComponent(txtIdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_nombreProducto))
                    .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreProducto)))
                .addGap(16, 16, 16))
        );
        panel_cont_icon_user3Layout.setVerticalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_id_entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreProducto)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lbl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lbl_precioEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_precioVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panel_cont_icon_user5.setForeground(new java.awt.Color(19, 22, 27));

        lbl_buscarP.setBackground(new java.awt.Color(0, 0, 0));
        lbl_buscarP.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        lbl_buscarP.setText("Buscar Producto");

        lbl_idProducto_1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_idProducto_1.setText("Nombre o ID Producto:");

        txtBuscarNameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarNameProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cont_icon_user5Layout = new javax.swing.GroupLayout(panel_cont_icon_user5);
        panel_cont_icon_user5.setLayout(panel_cont_icon_user5Layout);
        panel_cont_icon_user5Layout.setHorizontalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_buscarP)
                    .addComponent(lbl_idProducto_1)
                    .addComponent(txtBuscarNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panel_cont_icon_user5Layout.setVerticalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_buscarP)
                .addGap(28, 28, 28)
                .addComponent(lbl_idProducto_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_cont_icon_user7.setForeground(new java.awt.Color(19, 22, 27));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Complete la informacion de las entradas");

        javax.swing.GroupLayout panel_cont_icon_user7Layout = new javax.swing.GroupLayout(panel_cont_icon_user7);
        panel_cont_icon_user7.setLayout(panel_cont_icon_user7Layout);
        panel_cont_icon_user7Layout.setHorizontalGroup(
            panel_cont_icon_user7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_cont_icon_user7Layout.setVerticalGroup(
            panel_cont_icon_user7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cont_icon_user8.setForeground(new java.awt.Color(19, 22, 27));

        btnRegistrarEntrada.setBackground(new java.awt.Color(0, 102, 255));
        btnRegistrarEntrada.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRegistrarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/iconGuardar1.png"))); // NOI18N
        btnRegistrarEntrada.setText("Guardar");

        javax.swing.GroupLayout panel_cont_icon_user8Layout = new javax.swing.GroupLayout(panel_cont_icon_user8);
        panel_cont_icon_user8.setLayout(panel_cont_icon_user8Layout);
        panel_cont_icon_user8Layout.setHorizontalGroup(
            panel_cont_icon_user8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRegistrarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panel_cont_icon_user8Layout.setVerticalGroup(
            panel_cont_icon_user8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user8Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnRegistrarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_cont_icon_user6.setForeground(new java.awt.Color(19, 22, 27));

        btnEditarEntrada.setBackground(new java.awt.Color(0, 102, 255));
        btnEditarEntrada.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEditarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/iconEditar1.png"))); // NOI18N
        btnEditarEntrada.setText("Editar");

        btnEliminarEntrada.setBackground(new java.awt.Color(0, 102, 255));
        btnEliminarEntrada.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEliminarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-delete.png"))); // NOI18N
        btnEliminarEntrada.setText("Eliminar");

        javax.swing.GroupLayout panel_cont_icon_user6Layout = new javax.swing.GroupLayout(panel_cont_icon_user6);
        panel_cont_icon_user6.setLayout(panel_cont_icon_user6Layout);
        panel_cont_icon_user6Layout.setHorizontalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user6Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnEditarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(btnEliminarEntrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cont_icon_user6Layout.setVerticalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_cont_icon_user10.setForeground(new java.awt.Color(19, 22, 27));

        tblEntradas.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        tblEntradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEntradas.setRowHeight(15);
        tblEntradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntradasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEntradas);

        javax.swing.GroupLayout panel_cont_icon_user10Layout = new javax.swing.GroupLayout(panel_cont_icon_user10);
        panel_cont_icon_user10.setLayout(panel_cont_icon_user10Layout);
        panel_cont_icon_user10Layout.setHorizontalGroup(
            panel_cont_icon_user10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cont_icon_user10Layout.setVerticalGroup(
            panel_cont_icon_user10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_cont_icon_user11.setForeground(new java.awt.Color(19, 22, 27));

        tblTablaProductosABuscarEnt.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        tblTablaProductosABuscarEnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTablaProductosABuscarEnt.setRowHeight(15);
        tblTablaProductosABuscarEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaProductosABuscarEntMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTablaProductosABuscarEnt);

        javax.swing.GroupLayout panel_cont_icon_user11Layout = new javax.swing.GroupLayout(panel_cont_icon_user11);
        panel_cont_icon_user11.setLayout(panel_cont_icon_user11Layout);
        panel_cont_icon_user11Layout.setHorizontalGroup(
            panel_cont_icon_user11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panel_cont_icon_user11Layout.setVerticalGroup(
            panel_cont_icon_user11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_cont_icon_user2Layout = new javax.swing.GroupLayout(panel_cont_icon_user2);
        panel_cont_icon_user2.setLayout(panel_cont_icon_user2Layout);
        panel_cont_icon_user2Layout.setHorizontalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_cont_icon_user8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                                .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panel_cont_icon_user11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel_cont_icon_user10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont_icon_user6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panel_cont_icon_user7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        panel_cont_icon_user2Layout.setVerticalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_cont_icon_user7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_cont_icon_user11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_cont_icon_user10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_cont_icon_user6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_cont_icon_user8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(panel_cont_icon_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1100, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEntradaActionPerformed

    private void tblTablaProductosABuscarEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaProductosABuscarEntMouseClicked

    }//GEN-LAST:event_tblTablaProductosABuscarEntMouseClicked

    private void tblEntradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntradasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEntradasMouseClicked

    private void txtBuscarNameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarNameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarNameProductActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarEntrada;
    private javax.swing.JButton btnEliminarEntrada;
    private javax.swing.JButton btnRegistrarEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_buscarP;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_idProducto_1;
    private javax.swing.JLabel lbl_id_entrada;
    private javax.swing.JLabel lbl_nombreProducto;
    private javax.swing.JLabel lbl_precioEntrada;
    private javax.swing.JLabel lbl_precioVenta;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JPanel panel_cont_icon_user1;
    private javax.swing.JPanel panel_cont_icon_user10;
    private javax.swing.JPanel panel_cont_icon_user11;
    private javax.swing.JPanel panel_cont_icon_user2;
    private javax.swing.JPanel panel_cont_icon_user3;
    private javax.swing.JPanel panel_cont_icon_user5;
    private javax.swing.JPanel panel_cont_icon_user6;
    private javax.swing.JPanel panel_cont_icon_user7;
    private javax.swing.JPanel panel_cont_icon_user8;
    private javax.swing.JTable tblEntradas;
    private javax.swing.JTable tblTablaProductosABuscarEnt;
    private javax.swing.JTextField txtBuscarNameProduct;
    private javax.swing.JTextField txtCantidadP;
    private javax.swing.JTextField txtDescOperacion;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtIdEntrada;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtTotalE;
    // End of variables declaration//GEN-END:variables

    /**
     * Devuelve el botón para editar una entrada.
     *
     * @return el botón para editar una entrada
     */
    public JButton getBtnEditarEntrada() {
        return btnEditarEntrada;
    }

    /**
     * Devuelve el botón para eliminar una entrada.
     *
     * @return el botón para eliminar una entrada
     */
    public JButton getBtnEliminarEntrada() {
        return btnEliminarEntrada;
    }

    /**
     * Devuelve el botón para registrar una entrada.
     *
     * @return el botón para registrar una entrada
     */
    public JButton getBtnRegistrarEntrada() {
        return btnRegistrarEntrada;
    }

    /**
     * Devuelve el componente JLabel 1.
     *
     * @return el componente JLabel 1
     */
    public JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * Devuelve el componente JLabel 10.
     *
     * @return el componente JLabel 10
     */
    public JLabel getjLabel10() {
        return jLabel10;
    }

    /**
     * Devuelve el componente JLabel 11.
     *
     * @return el componente JLabel 11
     */
    public JLabel getjLabel11() {
        return jLabel11;
    }

    /**
     * Devuelve el componente JScrollPane 1.
     *
     * @return el componente JScrollPane 1
     */
    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * Devuelve el componente JScrollPane 2.
     *
     * @return el componente JScrollPane 2
     */
    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * Devuelve el componente JLabel para buscar productos.
     *
     * @return el componente JLabel para buscar productos
     */
    public JLabel getLbl_buscarP() {
        return lbl_buscarP;
    }

    /**
     * Devuelve el componente JLabel para la fecha.
     *
     * @return el componente JLabel para la fecha
     */
    public JLabel getLbl_fecha() {
        return lbl_fecha;
    }

    /**
     * Devuelve el componente JLabel para el ID del producto.
     *
     * @return el componente JLabel para el ID del producto
     */
    public JLabel getLbl_idProducto_1() {
        return lbl_idProducto_1;
    }

    /**
     * Devuelve el componente JLabel para el ID de la entrada.
     *
     * @return el componente JLabel para el ID de la entrada
     */
    public JLabel getLbl_id_entrada() {
        return lbl_id_entrada;
    }

    /**
     * Devuelve el componente JLabel para el nombre del producto.
     *
     * @return el componente JLabel para el nombre del producto
     */
    public JLabel getLbl_nombreProducto() {
        return lbl_nombreProducto;
    }

    /**
     * Devuelve el componente JLabel para el precio de entrada.
     *
     * @return el componente JLabel para el precio de entrada
     */
    public JLabel getLbl_precioEntrada() {
        return lbl_precioEntrada;
    }

    /**
     * Devuelve el componente JLabel para el precio de venta.
     *
     * @return el componente JLabel para el precio de venta
     */
    public JLabel getLbl_precioVenta() {
        return lbl_precioVenta;
    }

    /**
     * Devuelve el componente JLabel para el stock.
     *
     * @return el componente JLabel para el stock
     */
    public JLabel getLbl_stock() {
        return lbl_stock;
    }

    /**
     * Devuelve el componente JLabel para el total.
     *
     * @return el componente JLabel para el total
     */
    public JLabel getLbl_total() {
        return lbl_total;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 1.
     *
     * @return el panel contenedor de iconos de usuario 1
     */
    public JPanel getPanel_cont_icon_user1() {
        return panel_cont_icon_user1;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 10.
     *
     * @return el panel contenedor de iconos de usuario 10
     */
    public JPanel getPanel_cont_icon_user10() {
        return panel_cont_icon_user10;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 11.
     *
     * @return el panel contenedor de iconos de usuario 11
     */
    public JPanel getPanel_cont_icon_user11() {
        return panel_cont_icon_user11;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 2.
     *
     * @return el panel contenedor de iconos de usuario 2
     */
    public JPanel getPanel_cont_icon_user2() {
        return panel_cont_icon_user2;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 3.
     *
     * @return el panel contenedor de iconos de usuario 3
     */
    public JPanel getPanel_cont_icon_user3() {
        return panel_cont_icon_user3;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 5.
     *
     * @return el panel contenedor de iconos de usuario 5
     */
    public JPanel getPanel_cont_icon_user5() {
        return panel_cont_icon_user5;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 6.
     *
     * @return el panel contenedor de iconos de usuario 6
     */
    public JPanel getPanel_cont_icon_user6() {
        return panel_cont_icon_user6;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 7.
     *
     * @return el panel contenedor de iconos de usuario 7
     */
    public JPanel getPanel_cont_icon_user7() {
        return panel_cont_icon_user7;
    }

    /**
     * Devuelve el panel contenedor de iconos de usuario 8.
     *
     * @return el panel contenedor de iconos de usuario 8
     */
    public JPanel getPanel_cont_icon_user8() {
        return panel_cont_icon_user8;
    }

    /**
     * Devuelve la tabla de entradas.
     *
     * @return la tabla de entradas
     */
    public JTable getTblEntradas() {
        return tblEntradas;
    }

    /**
     * Devuelve la tabla de productos a buscar para las entradas.
     *
     * @return la tabla de productos a buscar para las entradas
     */
    public JTable getTblTablaProductosABuscarEnt() {
        return tblTablaProductosABuscarEnt;
    }

    /**
     * Devuelve el campo de texto para buscar el nombre del producto.
     *
     * @return el campo de texto para buscar el nombre del producto
     */
    public JTextField getTxtBuscarNameProduct() {
        return txtBuscarNameProduct;
    }

    /**
     * Devuelve el campo de texto para la cantidad del producto.
     *
     * @return el campo de texto para la cantidad del producto
     */
    public JTextField getTxtCantidadP() {
        return txtCantidadP;
    }

    /**
     * Devuelve el campo de texto para la descripción de la operación.
     *
     * @return el campo de texto para la descripción de la operación
     */
    public JTextField getTxtDescOperacion() {
        return txtDescOperacion;
    }

    /**
     * Devuelve el campo de texto para la fecha de entrada.
     *
     * @return el campo de texto para la fecha de entrada
     */
    public JTextField getTxtFechaEntrada() {
        return txtFechaEntrada;
    }

    /**
     * Devuelve el campo de texto para el ID de la entrada.
     *
     * @return el campo de texto para el ID de la entrada
     */
    public JTextField getTxtIdEntrada() {
        return txtIdEntrada;
    }

    /**
     * Devuelve el campo de texto para el ID del producto.
     *
     * @return el campo de texto para el ID del producto
     */
    public JTextField getTxtIdProducto() {
        return txtIdProducto;
    }

    /**
     * Devuelve el campo de texto para el nombre del producto.
     *
     * @return el campo de texto para el nombre del producto
     */
    public JTextField getTxtNombreProducto() {
        return txtNombreProducto;
    }

    /**
     * Devuelve el campo de texto para el precio unitario.
     *
     * @return el campo de texto para el precio unitario
     */
    public JTextField getTxtPrecioUnitario() {
        return txtPrecioUnitario;
    }

    /**
     * Devuelve el campo de texto para el total de la entrada.
     *
     * @return el campo de texto para el total de la entrada
     */
    public JTextField getTxtTotalE() {
        return txtTotalE;
    }
}
