package view;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import controller.ControladorEntrada;

import style.RoundedPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import controller.ControllerProducto;
import javax.swing.JPanel;

/**
 * Ventana principal del menú para el usuario (empleado).
 * <p>
 * Esta clase representa la interfaz principal que se muestra a los usuarios con
 * permisos limitados (tipoUsuario = 2). Proporciona acceso a diferentes vistas,
 * como la de registro de salidas, registro de productos, listado de salidas,
 * entre otros.
 * </p>
 * <p>
 * La ventana contiene un diseño de paneles dinámicos (CardLayout) que permite
 * cambiar entre diferentes vistas de la interfaz gráfica según el contexto del
 * usuario.
 * </p>
 *
 * @author Ralfph
 */
public class ViewMenuPrincipalUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuPrincipalUsuario
     */
    static private String nombre_usuario;
    static private int tipoUsuario;
    static private boolean verificador;
    CardLayout vista;

    VistaPrincipal vistap = new VistaPrincipal();
    ViewRegistroUsuario vistaUser = new ViewRegistroUsuario();
    ViewRegistroCategorias vistaCategorias = new ViewRegistroCategorias();
    ViewRegistroProductos vistaProductos = new ViewRegistroProductos();//SOOOOOL
    ViewRegistroEntradas vistaEntradas = new ViewRegistroEntradas();
    ViewVisualizador vistaVisualizador = new ViewVisualizador();
    ViewListadoSalidas vistaListadoSalidas = new ViewListadoSalidas(this, 2);
    ViewRegistroSalidas vistaRegistroSalidas = new ViewRegistroSalidas(this, 2);
    ViewRegistroProveedores vistaRegistroProveedor = new ViewRegistroProveedores();

    /**
     * Constructor de la ventana del menú principal para usuarios (empleados).
     * <p>
     * Configura la interfaz principal del usuario, mostrando el nombre del
     * usuario autenticado, ajustando el tamaño de la ventana y preparando el
     * sistema de navegación entre vistas.
     * </p>
     *
     * @param nombre_usuario Nombre del usuario autenticado que se muestra en la
     * interfaz.
     * @param tipoUsuario Tipo de usuario que determina qué vistas estarán
     * disponibles.
     */
    public ViewMenuPrincipalUsuario(String nombre_usuario, int tipoUsuario) {
        this.nombre_usuario = nombre_usuario;
        this.tipoUsuario = tipoUsuario;
        getContentPane().setBackground(Color.decode("#000511"));
        initComponents();
        lbl_usuario_rol.setText(nombre_usuario);
        this.setTitle("Menu Principal");
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);

        vista = (CardLayout) pnl_principal.getLayout();

        // Agrega los paneles al pnl_principal
        pnl_principal.add(vistap, "VistaPrincipalUsuario");
        pnl_principal.add(vistaVisualizador, "vistaVisualizador");
        pnl_principal.add(vistaUser, "RegistroUsuario");
        pnl_principal.add(vistaCategorias, "RegistroCategoria");
        pnl_principal.add(vistaProductos, "RegistroProducto");
        pnl_principal.add(vistaEntradas, "RegistroEntradas");
        pnl_principal.add(vistaListadoSalidas, "vistaListadoSalidas");
        pnl_principal.add(vistaRegistroSalidas, "RegistroSalidas");
        pnl_principal.add(vistaRegistroProveedor, "RegistroProveedor");

        vista.show(pnl_principal, "menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cont_menu_op = new RoundedPanel(60,new Color(19, 22, 27));
        btn_inicio = new javax.swing.JButton();
        btn_categoria = new javax.swing.JButton();
        btn_cerrar_sesion = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        btn_entrada = new javax.swing.JButton();
        btn_salida = new javax.swing.JButton();
        btn_proveedor = new javax.swing.JButton();
        lbl_icon_inicio = new javax.swing.JLabel();
        lbl_icon_categoria = new javax.swing.JLabel();
        lbl_icon_entrada = new javax.swing.JLabel();
        lbl_icon_salida = new javax.swing.JLabel();
        lbl_icon_proveedor = new javax.swing.JLabel();
        lbl_icon_cerrar_sesion = new javax.swing.JLabel();
        lbl_icon_producto = new javax.swing.JLabel();
        panel_cont_icon_user =  new RoundedPanel(60, new Color(19, 22, 27));
        lbl_icon_user = new javax.swing.JLabel();
        lbl_usuario_rol = new javax.swing.JLabel();
        pnl_principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_cont_menu_op.setBackground(new java.awt.Color(0, 0, 0));

        btn_inicio.setBackground(new java.awt.Color(19, 22, 27));
        btn_inicio.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btn_inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_inicio.setText("Inicio");
        btn_inicio.setBorder(null);
        btn_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_inicioMouseExited(evt);
            }
        });
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_categoria.setBackground(new java.awt.Color(19, 22, 27));
        btn_categoria.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btn_categoria.setForeground(new java.awt.Color(255, 255, 255));
        btn_categoria.setText("Categoria");
        btn_categoria.setBorder(null);
        btn_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_categoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_categoriaMouseExited(evt);
            }
        });
        btn_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoriaActionPerformed(evt);
            }
        });

        btn_cerrar_sesion.setBackground(new java.awt.Color(19, 22, 27));
        btn_cerrar_sesion.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btn_cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar_sesion.setText("Cerrar Sesion");
        btn_cerrar_sesion.setBorder(null);
        btn_cerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cerrar_sesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cerrar_sesionMouseExited(evt);
            }
        });
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });

        btn_producto.setBackground(new java.awt.Color(19, 22, 27));
        btn_producto.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btn_producto.setForeground(new java.awt.Color(255, 255, 255));
        btn_producto.setText("Productos");
        btn_producto.setBorder(null);
        btn_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_productoMouseExited(evt);
            }
        });
        btn_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productoActionPerformed(evt);
            }
        });

        btn_entrada.setBackground(new java.awt.Color(19, 22, 27));
        btn_entrada.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btn_entrada.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrada.setText("Entradas");
        btn_entrada.setBorder(null);
        btn_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_entradaMouseExited(evt);
            }
        });
        btn_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entradaActionPerformed(evt);
            }
        });

        btn_salida.setBackground(new java.awt.Color(19, 22, 27));
        btn_salida.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btn_salida.setForeground(new java.awt.Color(255, 255, 255));
        btn_salida.setText("Salidas");
        btn_salida.setBorder(null);
        btn_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salidaMouseExited(evt);
            }
        });
        btn_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salidaActionPerformed(evt);
            }
        });

        btn_proveedor.setBackground(new java.awt.Color(19, 22, 27));
        btn_proveedor.setFont(new java.awt.Font("Gill Sans MT", 0, 20)); // NOI18N
        btn_proveedor.setForeground(new java.awt.Color(255, 255, 255));
        btn_proveedor.setText("Proveedor");
        btn_proveedor.setBorder(null);
        btn_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_proveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_proveedorMouseExited(evt);
            }
        });
        btn_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedorActionPerformed(evt);
            }
        });

        lbl_icon_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/Home.png"))); // NOI18N

        lbl_icon_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/Layers.png"))); // NOI18N

        lbl_icon_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/Plus.png"))); // NOI18N

        lbl_icon_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/Edit.png"))); // NOI18N

        lbl_icon_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/Truck.png"))); // NOI18N

        lbl_icon_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/Log out.png"))); // NOI18N

        lbl_icon_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/Package.png"))); // NOI18N

        javax.swing.GroupLayout panel_cont_menu_opLayout = new javax.swing.GroupLayout(panel_cont_menu_op);
        panel_cont_menu_op.setLayout(panel_cont_menu_opLayout);
        panel_cont_menu_opLayout.setHorizontalGroup(
            panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_menu_opLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lbl_icon_cerrar_sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cerrar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_menu_opLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_icon_inicio)
                    .addComponent(lbl_icon_categoria)
                    .addComponent(lbl_icon_entrada)
                    .addComponent(lbl_icon_salida)
                    .addComponent(lbl_icon_proveedor)
                    .addComponent(lbl_icon_producto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_salida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_entrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_producto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_categoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_inicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_cont_menu_opLayout.setVerticalGroup(
            panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_icon_inicio)))
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbl_icon_categoria)))
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbl_icon_producto)))
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_icon_entrada)
                        .addGap(55, 55, 55)
                        .addComponent(lbl_icon_salida))
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_cont_menu_opLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_icon_proveedor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(panel_cont_menu_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_menu_opLayout.createSequentialGroup()
                        .addComponent(btn_cerrar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_menu_opLayout.createSequentialGroup()
                        .addComponent(lbl_icon_cerrar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        panel_cont_icon_user.setForeground(new java.awt.Color(19, 22, 27));

        lbl_icon_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons_menu_principal/userIconDashboard1.png"))); // NOI18N

        lbl_usuario_rol.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_usuario_rol.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_cont_icon_userLayout = new javax.swing.GroupLayout(panel_cont_icon_user);
        panel_cont_icon_user.setLayout(panel_cont_icon_userLayout);
        panel_cont_icon_userLayout.setHorizontalGroup(
            panel_cont_icon_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_userLayout.createSequentialGroup()
                .addComponent(lbl_icon_user)
                .addGap(18, 18, 18)
                .addComponent(lbl_usuario_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_cont_icon_userLayout.setVerticalGroup(
            panel_cont_icon_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_userLayout.createSequentialGroup()
                .addComponent(lbl_icon_user)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_cont_icon_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_usuario_rol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_principal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_cont_icon_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_cont_menu_op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_cont_icon_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_cont_menu_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(pnl_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método getter para acceder al CardLayout utilizado para gestionar las
     * vistas.
     * <p>
     * Este método devuelve la instancia del objeto `CardLayout` que controla la
     * visualización de los diferentes paneles en la interfaz gráfica. A través
     * de este objeto, se pueden cambiar dinámicamente entre las diferentes
     * vistas registro de salidas y listado de salidas.
     * </p>
     *
     * @return El objeto `CardLayout` utilizado para cambiar entre vistas.
     */
    // Getter para acceder al CardLayout
    public CardLayout getVista() {
        return vista;
    }

    /**
     * Método getter para acceder al JPanel principal que contiene las vistas.
     * <p>
     * Este método devuelve el panel principal (`JPanel`) que contiene todos los
     * subpaneles de la interfaz gráfica. El `JPanel` principal es el contenedor
     * sobre el cual se añaden y muestran los diferentes paneles del sistema.
     * </p>
     *
     * @return El objeto `JPanel` principal que gestiona las vistas de la
     * interfaz.
     */
    // Getter para acceder al JPanel principal
    public JPanel getPnlPrincipal() {
        return pnl_principal;
    }
    private void btn_inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseEntered
        //btn_home.setBackground(Color.ORANGE); // Cambia el color al pasar el mouse
    }//GEN-LAST:event_btn_inicioMouseEntered

    private void btn_inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseExited
        //btn_home.setBackground(Color.BLACK); // Vuelve al color original al salir el mouse
    }//GEN-LAST:event_btn_inicioMouseExited
    /**
     * Cambia la vista al menú principal.
     * <p>
     * Actualiza el título de la ventana y asegura que el panel principal se
     * actualice correctamente.
     * </p>
     *
     * @param evt Evento de clic del botón de inicio.
     */
    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        vista.show(pnl_principal, "VistaPrincipalUsuario");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        this.setTitle("Menu Principal");

    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_categoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_categoriaMouseEntered

    private void btn_categoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoriaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_categoriaMouseExited

    /**
     * Cambia la vista a la sección de gestión de categorías.
     * <p>
     * Actualiza el título de la ventana a "Gestion de categorias".
     * </p>
     *
     * @param evt Evento de clic del botón de categoría.
     */
    private void btn_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoriaActionPerformed
        vista.show(pnl_principal, "RegistroCategoria");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        this.setTitle("Gestion de categorias");

    }//GEN-LAST:event_btn_categoriaActionPerformed

    private void btn_cerrar_sesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrar_sesionMouseEntered

    private void btn_cerrar_sesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrar_sesionMouseExited

    /**
     * Cambia la vista de la aplicación al inicio de sesión.
     * <p>
     * Cierra la ventana actual para retornar a la vista de inicio de sesión.
     * </p>
     *
     * @param evt Evento de clic del botón para salir al inicio de sesión.
     */
    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        ViewInicioSesion viewInicio = new ViewInicioSesion();
        viewInicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    private void btn_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productoMouseEntered

    }//GEN-LAST:event_btn_productoMouseEntered

    private void btn_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_productoMouseExited

    /**
     * Cambia la vista a la sección de gestión de productos.
     * <p>
     * Actualiza el título de la ventana a "Gestion de productos" y establece el
     * controlador de productos.
     * </p>
     *
     * @param evt Evento de clic del botón de productos.
     */
    private void btn_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productoActionPerformed
        vista.show(pnl_principal, "RegistroProducto");
        ControllerProducto controlador = new ControllerProducto(vistaProductos);//SOOOOO0L
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        this.setTitle("Gestion de productos");
    }//GEN-LAST:event_btn_productoActionPerformed

    private void btn_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entradaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_entradaMouseEntered

    private void btn_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entradaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_entradaMouseExited

    /**
     * Cambia la vista a la sección de gestion de entradas.
     * <p>
     * Actualiza el título de la ventana a "gestion de entradas".
     * </p>
     *
     * @param evt Evento de clic del botón de entradas.
     */
    private void btn_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entradaActionPerformed
        vista.show(pnl_principal, "RegistroEntradas");
        ControladorEntrada controladorEntrad = new ControladorEntrada(vistaEntradas);//SOOOOO0L
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        this.setTitle("Gestion de entradas de productos");
    }//GEN-LAST:event_btn_entradaActionPerformed

    private void btn_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salidaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salidaMouseEntered

    private void btn_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salidaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salidaMouseExited

    /**
     * Cambia la vista a la sección de gestión de salidas.
     * <p>
     * Actualiza el título de la ventana a "Listado de salidas".
     * </p>
     *
     * @param evt Evento de clic del botón de salidas.
     */
    private void btn_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidaActionPerformed
        vista.show(pnl_principal, "vistaListadoSalidas");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        this.setTitle("Listado de salidas");
    }//GEN-LAST:event_btn_salidaActionPerformed

    private void btn_proveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedorMouseEntered

    private void btn_proveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedorMouseExited

    private void btn_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedorActionPerformed
        vista.show(pnl_principal, "RegistroProveedor");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        this.setTitle("Registro de Proveedor");
    }//GEN-LAST:event_btn_proveedorActionPerformed

    private void btn_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedorMouseClicked
        vista.show(pnl_principal, "RegistroProveedor");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        this.setTitle("Registro de Proveedor");    }//GEN-LAST:event_btn_proveedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
            //FlatMacDarkLaf
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPrincipalUsuario(nombre_usuario, 2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_categoria;
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JButton btn_entrada;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_producto;
    private javax.swing.JButton btn_proveedor;
    private javax.swing.JButton btn_salida;
    private javax.swing.JLabel lbl_icon_categoria;
    private javax.swing.JLabel lbl_icon_cerrar_sesion;
    private javax.swing.JLabel lbl_icon_entrada;
    private javax.swing.JLabel lbl_icon_inicio;
    private javax.swing.JLabel lbl_icon_producto;
    private javax.swing.JLabel lbl_icon_proveedor;
    private javax.swing.JLabel lbl_icon_salida;
    private javax.swing.JLabel lbl_icon_user;
    private javax.swing.JLabel lbl_usuario_rol;
    private javax.swing.JPanel panel_cont_icon_user;
    private static javax.swing.JPanel panel_cont_menu_op;
    private static javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
