package view;

import controller.ControllerSalida;
import style.RoundedPanel;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Panel de registro de salidas en la interfaz gráfica de la aplicación.
 * <p>
 * Esta clase define el panel para la vista de registro de salidas en el
 * sistema. Permite gestionar y registrar las salidas de inventario o productos,
 * adaptándose según el tipo de usuario que acceda (administrador o empleado).
 * </p>
 *
 * <p>
 * Incluye configuraciones personalizadas de fondo y soporte para interacción
 * con el menú principal según el rol del usuario.
 * </p>
 *
 * @author Ralfph
 */
public class ViewRegistroSalidas extends javax.swing.JPanel {

    /**
     * Referencia al menú principal del administrador.
     */
    private ViewMenuPrincipal vistaPrincipalParent;
    /**
     * Referencia al menú principal del usuario estándar (empleado).
     */
    private ViewMenuPrincipalUsuario vistaPrincipalParentUser;
    /**
     * Indica el tipo de usuario que accede al panel.
     * <p>
     * 1: Administrador. <br>
     * 2: Usuario estándar (Empleado).
     * </p>
     */
    private int tipoUsuario;

    /**
     * Constructor que inicializa el panel de registro de salidas para el
     * administrador.
     * <p>
     * Este constructor configura el panel con un fondo personalizado y
     * establece una referencia al menú principal del administrador para
     * permitir la navegación y acciones relacionadas con las salidas de
     * inventario.
     * </p>
     *
     * @param vistaPrincipalParent referencia al menú principal del
     * administrador (instancia de {@link ViewMenuPrincipal}).
     * @param tipoUsuario tipo de usuario (en este caso, debe ser 1 para
     * administrador).
     */
    public ViewRegistroSalidas(ViewMenuPrincipal vistaPrincipalParent, int tipoUsuario) {
        this.vistaPrincipalParent = vistaPrincipalParent;
        this.tipoUsuario = tipoUsuario;
        this.setBackground(Color.decode("#000511"));
        initComponents();
        
        ControllerSalida controlador = new ControllerSalida(this);

    }

    /**
     * Constructor que inicializa el panel de registro de salidas para el
     * empleado.
     * <p>
     * Este constructor configura el panel con un fondo personalizado y
     * establece una referencia al menú principal del usuario estándar
     * (empleado) para permitir la navegación y acciones relacionadas con las
     * salidas de inventario.
     * </p>
     *
     * @param vistaPrincipalParentUsuario referencia al menú principal del
     * usuario estándar (instancia de {@link ViewMenuPrincipalUsuario}).
     * @param tipoUsuario tipo de usuario (en este caso, debe ser 2 para
     * empleado).
     */
    public ViewRegistroSalidas(ViewMenuPrincipalUsuario vistaPrincipalParentUsuario, int tipoUsuario) {
        this.vistaPrincipalParentUser = vistaPrincipalParentUsuario;
        this.tipoUsuario = tipoUsuario;
        this.setBackground(Color.decode("#000511"));
        initComponents();
        ControllerSalida controlador = new ControllerSalida(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cont =  new RoundedPanel(60, new Color(19, 22, 27));
        jLabel10 = new javax.swing.JLabel();
        lbl_return = new javax.swing.JLabel();
        panel_cont1 =  new RoundedPanel(30, new Color(19, 22, 27));
        panel_cont2 =  new RoundedPanel(30, Color.WHITE);
        lbl_id_salida = new javax.swing.JLabel();
        lbl_stock = new javax.swing.JLabel();
        txtField_id_salida = new javax.swing.JTextField();
        txtField_stockDisponible = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        txtField_nombre = new javax.swing.JTextField();
        txtField_cantidad = new javax.swing.JTextField();
        txtField_precio = new javax.swing.JTextField();
        txtField_fecha_salida = new javax.swing.JTextField();
        lbl_buscar4 = new javax.swing.JLabel();
        panel_cont3 =  new RoundedPanel(60, new Color(0,5,17));
        lbl_num_salida = new javax.swing.JLabel();
        lbl_cont_salida = new javax.swing.JLabel();
        panel_cont4 =  new RoundedPanel(30, Color.WHITE);
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_salidas = new javax.swing.JTable();
        panel_cont5 =  new RoundedPanel(60, new Color(0,5,17));
        lbl_generar = new javax.swing.JLabel();
        panel_cont_icon_user13 =  new RoundedPanel(30, Color.WHITE);
        lbl_subtotal = new javax.swing.JLabel();
        txtField_subtotal = new javax.swing.JTextField();
        lbl_igv = new javax.swing.JLabel();
        txtField_igv = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        txtField_total = new javax.swing.JTextField();
        panel_cont6 =  new RoundedPanel(60, new Color(0,5,17));
        lbl_restar = new javax.swing.JLabel();
        lbl_delete = new javax.swing.JLabel();
        lbl_agregar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(839, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont.setForeground(new java.awt.Color(19, 22, 27));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registro de Salidas");

        lbl_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-regresar.png"))); // NOI18N
        lbl_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_returnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_contLayout = new javax.swing.GroupLayout(panel_cont);
        panel_cont.setLayout(panel_contLayout);
        panel_contLayout.setHorizontalGroup(
            panel_contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_return)
                .addContainerGap())
        );
        panel_contLayout.setVerticalGroup(
            panel_contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_contLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_return))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(panel_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1100, 60));

        panel_cont1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont1.setForeground(new java.awt.Color(19, 22, 27));

        panel_cont2.setForeground(new java.awt.Color(19, 22, 27));

        lbl_id_salida.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_id_salida.setText("ID Salida :");

        lbl_stock.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_stock.setText("Stock Disponible :");

        txtField_id_salida.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        txtField_stockDisponible.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        lbl_nombre.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_nombre.setText("Nombre :");

        lbl_precio.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_precio.setText("Precio :");

        lblFechaSalida.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblFechaSalida.setText("Fecha Salida :");

        lbl_cantidad.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_cantidad.setText("Cantidad :");

        txtField_nombre.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        txtField_cantidad.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        txtField_precio.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        txtField_fecha_salida.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        lbl_buscar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-buscar.png"))); // NOI18N

        javax.swing.GroupLayout panel_cont2Layout = new javax.swing.GroupLayout(panel_cont2);
        panel_cont2.setLayout(panel_cont2Layout);
        panel_cont2Layout.setHorizontalGroup(
            panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont2Layout.createSequentialGroup()
                        .addComponent(lbl_id_salida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_nombre)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont2Layout.createSequentialGroup()
                        .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtField_stockDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtField_id_salida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont2Layout.createSequentialGroup()
                                .addComponent(lbl_precio)
                                .addGap(167, 167, 167))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont2Layout.createSequentialGroup()
                                .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtField_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtField_nombre))
                                .addGap(61, 61, 61))))
                    .addGroup(panel_cont2Layout.createSequentialGroup()
                        .addComponent(lbl_stock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont2Layout.createSequentialGroup()
                        .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_cont2Layout.createSequentialGroup()
                                .addComponent(lblFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45))
                            .addComponent(txtField_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont2Layout.createSequentialGroup()
                        .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtField_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lbl_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addComponent(lbl_buscar4)
                        .addGap(42, 42, 42))))
        );
        panel_cont2Layout.setVerticalGroup(
            panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_cont2Layout.createSequentialGroup()
                        .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id_salida)
                            .addComponent(lbl_nombre)
                            .addComponent(lbl_cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtField_id_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_buscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSalida)
                    .addComponent(lbl_stock)
                    .addComponent(lbl_precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cont2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_stockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panel_cont3.setForeground(new java.awt.Color(19, 22, 27));

        lbl_num_salida.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_num_salida.setForeground(new java.awt.Color(255, 255, 255));
        lbl_num_salida.setText("Numero de salida :");

        lbl_cont_salida.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_cont_salida.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cont_salida.setText("Complete la información de cada Salida");

        javax.swing.GroupLayout panel_cont3Layout = new javax.swing.GroupLayout(panel_cont3);
        panel_cont3.setLayout(panel_cont3Layout);
        panel_cont3Layout.setHorizontalGroup(
            panel_cont3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont3Layout.createSequentialGroup()
                .addContainerGap(803, Short.MAX_VALUE)
                .addComponent(lbl_num_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(panel_cont3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_cont3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lbl_cont_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
        panel_cont3Layout.setVerticalGroup(
            panel_cont3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_num_salida, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_cont3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_cont3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_cont_salida, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panel_cont4.setForeground(new java.awt.Color(19, 22, 27));

        tbl_salidas.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        tbl_salidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Salida", "ID Entrada", "Producto", "Precio U.", "Cantidad", "Importe"
            }
        ));
        tbl_salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_salidasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_salidas);

        javax.swing.GroupLayout panel_cont4Layout = new javax.swing.GroupLayout(panel_cont4);
        panel_cont4.setLayout(panel_cont4Layout);
        panel_cont4Layout.setHorizontalGroup(
            panel_cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        panel_cont4Layout.setVerticalGroup(
            panel_cont4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cont5.setForeground(new java.awt.Color(19, 22, 27));

        lbl_generar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-generar.png"))); // NOI18N

        panel_cont_icon_user13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user13.setForeground(new java.awt.Color(19, 22, 27));

        lbl_subtotal.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_subtotal.setText("Sub Total :");

        txtField_subtotal.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        lbl_igv.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_igv.setText("IGV :");

        txtField_igv.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        txtField_igv.setText("0.18");

        lbl_total.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_total.setText("Total :");

        txtField_total.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_cont_icon_user13Layout = new javax.swing.GroupLayout(panel_cont_icon_user13);
        panel_cont_icon_user13.setLayout(panel_cont_icon_user13Layout);
        panel_cont_icon_user13Layout.setHorizontalGroup(
            panel_cont_icon_user13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_cont_icon_user13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_igv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_subtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cont_icon_user13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField_total)
                    .addComponent(txtField_igv)
                    .addComponent(txtField_subtotal))
                .addContainerGap())
        );
        panel_cont_icon_user13Layout.setVerticalGroup(
            panel_cont_icon_user13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_cont_icon_user13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_subtotal)
                    .addComponent(txtField_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panel_cont_icon_user13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_igv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_igv))
                .addGap(31, 31, 31)
                .addGroup(panel_cont_icon_user13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_total))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout panel_cont5Layout = new javax.swing.GroupLayout(panel_cont5);
        panel_cont5.setLayout(panel_cont5Layout);
        panel_cont5Layout.setHorizontalGroup(
            panel_cont5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_cont_icon_user13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_generar)
                .addGap(82, 82, 82))
        );
        panel_cont5Layout.setVerticalGroup(
            panel_cont5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_cont_icon_user13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        panel_cont6.setForeground(new java.awt.Color(19, 22, 27));

        lbl_restar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-start.png"))); // NOI18N

        lbl_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-delete.png"))); // NOI18N

        lbl_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-agregar.png"))); // NOI18N

        javax.swing.GroupLayout panel_cont6Layout = new javax.swing.GroupLayout(panel_cont6);
        panel_cont6.setLayout(panel_cont6Layout);
        panel_cont6Layout.setHorizontalGroup(
            panel_cont6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel_cont6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_delete)
                    .addComponent(lbl_restar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_agregar)
                .addGap(26, 26, 26))
        );
        panel_cont6Layout.setVerticalGroup(
            panel_cont6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_restar)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout panel_cont1Layout = new javax.swing.GroupLayout(panel_cont1);
        panel_cont1.setLayout(panel_cont1Layout);
        panel_cont1Layout.setHorizontalGroup(
            panel_cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_cont3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_cont1Layout.createSequentialGroup()
                        .addGroup(panel_cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_cont2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panel_cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_cont1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(panel_cont5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_cont1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel_cont6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        panel_cont1Layout.setVerticalGroup(
            panel_cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_cont3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_cont1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont1Layout.createSequentialGroup()
                        .addComponent(panel_cont2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_cont4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_cont1Layout.createSequentialGroup()
                        .addComponent(panel_cont5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panel_cont6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panel_cont1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1100, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_salidasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_salidasMouseClicked

    /**
     * Cambia la vista al listado de salidas.
     * <p>
     * Este método responde al clic del botón relacionado con el listado de
     * salidas, actualizando la vista dinámica del sistema para mostrar el panel
     * del listado correspondiente. También actualiza el título de la ventana
     * según el tipo de usuario que accede (administrador o empleado). En caso
     * de que no se pueda determinar el contexto del usuario, muestra un mensaje
     * de error.
     * </p>
     *
     * @param evt Evento de clic del botón de listado de salidas (generado por
     * el usuario).
     */
    private void lbl_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnMouseClicked
        if (tipoUsuario == 1) {
            vistaPrincipalParent.getVista().show(vistaPrincipalParent.getPnlPrincipal(), "vistaListadoSalidas");
            vistaPrincipalParent.setTitle("Listado de salidas");
        } else if (tipoUsuario == 2) {
            vistaPrincipalParentUser.getVista().show(vistaPrincipalParentUser.getPnlPrincipal(), "vistaListadoSalidas");
            vistaPrincipalParentUser.setTitle("Listado de salidas");
        } else {
            JOptionPane.showMessageDialog(null, "Error: no se pudo determinar el contexto del usuario.");
        }
    }//GEN-LAST:event_lbl_returnMouseClicked

    public JLabel getLbl_agregar() {
        return lbl_agregar;
    }

    public JLabel getLbl_buscar4() {
        return lbl_buscar4;
    }

    public JLabel getLbl_delete() {
        return lbl_delete;
    }

    public JLabel getLbl_generar() {
        return lbl_generar;
    }

    public JLabel getLbl_restar() {
        return lbl_restar;
    }

    public JTable getTbl_salidas() {
        return tbl_salidas;
    }

    public JTextField getTxtField_cantidad() {
        return txtField_cantidad;
    }

    public JTextField getTxtField_fecha_salida() {
        return txtField_fecha_salida;
    }

    public JTextField getTxtField_id_salida() {
        return txtField_id_salida;
    }

    public JTextField getTxtField_igv() {
        return txtField_igv;
    }

    public JTextField getTxtField_nombre() {
        return txtField_nombre;
    }

    public JTextField getTxtField_precio() {
        return txtField_precio;
    }

    public JTextField getTxtField_stockDisponible() {
        return txtField_stockDisponible;
    }

    public JTextField getTxtField_subtotal() {
        return txtField_subtotal;
    }

    public JTextField getTxtField_total() {
        return txtField_total;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lbl_agregar;
    private javax.swing.JLabel lbl_buscar4;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_cont_salida;
    private javax.swing.JLabel lbl_delete;
    private javax.swing.JLabel lbl_generar;
    private javax.swing.JLabel lbl_id_salida;
    private javax.swing.JLabel lbl_igv;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_num_salida;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_restar;
    private javax.swing.JLabel lbl_return;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JPanel panel_cont;
    private javax.swing.JPanel panel_cont1;
    private javax.swing.JPanel panel_cont2;
    private javax.swing.JPanel panel_cont3;
    private javax.swing.JPanel panel_cont4;
    private javax.swing.JPanel panel_cont5;
    private javax.swing.JPanel panel_cont6;
    private javax.swing.JPanel panel_cont_icon_user13;
    private javax.swing.JTable tbl_salidas;
    private javax.swing.JTextField txtField_cantidad;
    private javax.swing.JTextField txtField_fecha_salida;
    private javax.swing.JTextField txtField_id_salida;
    private javax.swing.JTextField txtField_igv;
    private javax.swing.JTextField txtField_nombre;
    private javax.swing.JTextField txtField_precio;
    private javax.swing.JTextField txtField_stockDisponible;
    private javax.swing.JTextField txtField_subtotal;
    private javax.swing.JTextField txtField_total;
    // End of variables declaration//GEN-END:variables
}
