package view;

import style.RoundedPanel;
import java.awt.Color;

/**
 * Panel de registro de Registro de entradas en la interfaz gráfica de la aplicación.
 * <p>
 * Esta clase define el panel para la vista de registro de entradas, con un
 * fondo personalizado.
 * </p>
 *
 * @author Ralfph
 */
public class ViewRegistroEntradas extends javax.swing.JPanel {

    /**
     * Constructor que inicializa el panel de registro de entradas y establece
     * el color de fondo.
     */
    public ViewRegistroEntradas() {
        this.setBackground(Color.decode("#000511"));
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cont_icon_user1 =  new RoundedPanel(60, new Color(19, 22, 27));
        jLabel10 = new javax.swing.JLabel();
        panel_cont_icon_user2 =  new RoundedPanel(30, new Color(19, 22, 27));
        panel_cont_icon_user3 =  new RoundedPanel(30, Color.WHITE);
        lbl_id_entrada = new javax.swing.JLabel();
        txtidentrada = new javax.swing.JTextField();
        lbl_nombreProducto = new javax.swing.JLabel();
        txtnombreProducto = new javax.swing.JTextField();
        lbl_stock = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_precioEntrada = new javax.swing.JLabel();
        lbl_precioVenta = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        txtTotal1 = new javax.swing.JTextField();
        txtField_fecha = new javax.swing.JTextField();
        txtField_stock = new javax.swing.JTextField();
        txtField_precioV = new javax.swing.JTextField();
        txtField_precioEntrada = new javax.swing.JTextField();
        panel_cont_icon_user5 =  new RoundedPanel(30, Color.WHITE);
        lbl_buscarP = new javax.swing.JLabel();
        lbl_idProducto_1 = new javax.swing.JLabel();
        txtidProducto = new javax.swing.JTextField();
        lbl_buscar1 = new javax.swing.JLabel();
        panel_cont_icon_user7 =  new RoundedPanel(60, new Color(0,5,17));
        jLabel11 = new javax.swing.JLabel();
        panel_cont_icon_user8 =  new RoundedPanel(60, new Color(0,5,17));
        lbl_saved = new javax.swing.JLabel();
        panel_cont_icon_user6 =  new RoundedPanel(60, new Color(0, 5, 17));
        lbl_buscar = new javax.swing.JLabel();
        lbl_editar = new javax.swing.JLabel();
        lbl_delete = new javax.swing.JLabel();
        lbl_guardar = new javax.swing.JLabel();
        panel_cont_icon_user10 =  new RoundedPanel(30, Color.WHITE);
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_entradas2 = new javax.swing.JTable();
        panel_cont_icon_user11 =  new RoundedPanel(30, Color.WHITE);
        lbl_datosProveedor = new javax.swing.JLabel();
        lbl_id_Proveedor = new javax.swing.JLabel();
        txtidproveedor = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtproveedor = new javax.swing.JTextField();
        lbl_buscar2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(839, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cont_icon_user1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user1.setForeground(new java.awt.Color(19, 22, 27));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registro de Entradas");

        javax.swing.GroupLayout panel_cont_icon_user1Layout = new javax.swing.GroupLayout(panel_cont_icon_user1);
        panel_cont_icon_user1.setLayout(panel_cont_icon_user1Layout);
        panel_cont_icon_user1Layout.setHorizontalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panel_cont_icon_user1Layout.setVerticalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panel_cont_icon_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1100, 60));

        panel_cont_icon_user2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user2.setForeground(new java.awt.Color(19, 22, 27));

        panel_cont_icon_user3.setForeground(new java.awt.Color(19, 22, 27));

        lbl_id_entrada.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_id_entrada.setText("ID Entrada");

        txtidentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidentradaActionPerformed(evt);
            }
        });

        lbl_nombreProducto.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_nombreProducto.setText("Nombre Producto");

        lbl_stock.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_stock.setText("Stock");

        lbl_fecha.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_fecha.setText("Fecha");

        lbl_precioEntrada.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_precioEntrada.setText("Precio Entrada.");

        lbl_precioVenta.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_precioVenta.setText("Precio Venta");

        lbl_total.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_total.setText("Total");

        javax.swing.GroupLayout panel_cont_icon_user3Layout = new javax.swing.GroupLayout(panel_cont_icon_user3);
        panel_cont_icon_user3.setLayout(panel_cont_icon_user3Layout);
        panel_cont_icon_user3Layout.setHorizontalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_nombreProducto)
                                .addComponent(txtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_stock)
                                .addComponent(txtField_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_id_entrada)
                            .addComponent(txtidentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField_fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtField_precioEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtField_precioV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_total)
                                    .addComponent(lbl_precioVenta)
                                    .addComponent(lbl_precioEntrada)
                                    .addComponent(lbl_fecha))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel_cont_icon_user3Layout.setVerticalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_id_entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nombreProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_stock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtField_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtField_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lbl_precioEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtField_precioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_precioVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtField_precioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel_cont_icon_user5.setForeground(new java.awt.Color(19, 22, 27));

        lbl_buscarP.setBackground(new java.awt.Color(0, 0, 0));
        lbl_buscarP.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        lbl_buscarP.setText("Buscar Producto");

        lbl_idProducto_1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_idProducto_1.setText("ID Producto");

        lbl_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-buscar.png"))); // NOI18N

        javax.swing.GroupLayout panel_cont_icon_user5Layout = new javax.swing.GroupLayout(panel_cont_icon_user5);
        panel_cont_icon_user5.setLayout(panel_cont_icon_user5Layout);
        panel_cont_icon_user5Layout.setHorizontalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_buscarP)
                .addGap(129, 129, 129))
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idProducto_1)
                    .addComponent(txtidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(lbl_buscar1)
                .addGap(41, 41, 41))
        );
        panel_cont_icon_user5Layout.setVerticalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_buscarP)
                .addGroup(panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_idProducto_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_buscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        panel_cont_icon_user7.setForeground(new java.awt.Color(19, 22, 27));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Complete la informacion de las entradas");

        javax.swing.GroupLayout panel_cont_icon_user7Layout = new javax.swing.GroupLayout(panel_cont_icon_user7);
        panel_cont_icon_user7.setLayout(panel_cont_icon_user7Layout);
        panel_cont_icon_user7Layout.setHorizontalGroup(
            panel_cont_icon_user7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_cont_icon_user7Layout.setVerticalGroup(
            panel_cont_icon_user7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cont_icon_user8.setForeground(new java.awt.Color(19, 22, 27));

        lbl_saved.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-guardar.png"))); // NOI18N

        javax.swing.GroupLayout panel_cont_icon_user8Layout = new javax.swing.GroupLayout(panel_cont_icon_user8);
        panel_cont_icon_user8.setLayout(panel_cont_icon_user8Layout);
        panel_cont_icon_user8Layout.setHorizontalGroup(
            panel_cont_icon_user8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lbl_saved)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cont_icon_user8Layout.setVerticalGroup(
            panel_cont_icon_user8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user8Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lbl_saved)
                .addGap(9, 9, 9))
        );

        panel_cont_icon_user6.setForeground(new java.awt.Color(19, 22, 27));

        lbl_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-buscar.png"))); // NOI18N

        lbl_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-editar.png"))); // NOI18N

        lbl_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-eliminar.png"))); // NOI18N

        lbl_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-saved.png"))); // NOI18N

        javax.swing.GroupLayout panel_cont_icon_user6Layout = new javax.swing.GroupLayout(panel_cont_icon_user6);
        panel_cont_icon_user6.setLayout(panel_cont_icon_user6Layout);
        panel_cont_icon_user6Layout.setHorizontalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user6Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lbl_editar)
                .addGap(136, 136, 136)
                .addComponent(lbl_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_buscar)
                .addGap(59, 59, 59)
                .addComponent(lbl_guardar)
                .addGap(18, 18, 18))
        );
        panel_cont_icon_user6Layout.setVerticalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panel_cont_icon_user10.setForeground(new java.awt.Color(19, 22, 27));

        tbl_entradas2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        tbl_entradas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Stock", "Fecha", "ID proveedor", "Precio Entrada", "Precio Venta", "Total"
            }
        ));
        tbl_entradas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_entradas2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_entradas2);

        javax.swing.GroupLayout panel_cont_icon_user10Layout = new javax.swing.GroupLayout(panel_cont_icon_user10);
        panel_cont_icon_user10.setLayout(panel_cont_icon_user10Layout);
        panel_cont_icon_user10Layout.setHorizontalGroup(
            panel_cont_icon_user10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        panel_cont_icon_user10Layout.setVerticalGroup(
            panel_cont_icon_user10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cont_icon_user11.setForeground(new java.awt.Color(19, 22, 27));

        lbl_datosProveedor.setBackground(new java.awt.Color(0, 0, 0));
        lbl_datosProveedor.setFont(new java.awt.Font("Gill Sans MT", 0, 17)); // NOI18N
        lbl_datosProveedor.setText("Datos del Proveedor");

        lbl_id_Proveedor.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_id_Proveedor.setText("ID");

        lblNombre.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lblNombre.setText("Nombre");

        lbl_buscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-buscar.png"))); // NOI18N

        javax.swing.GroupLayout panel_cont_icon_user11Layout = new javax.swing.GroupLayout(panel_cont_icon_user11);
        panel_cont_icon_user11.setLayout(panel_cont_icon_user11Layout);
        panel_cont_icon_user11Layout.setHorizontalGroup(
            panel_cont_icon_user11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel_cont_icon_user11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_cont_icon_user11Layout.createSequentialGroup()
                        .addComponent(lbl_id_Proveedor)
                        .addGap(80, 80, 80)
                        .addComponent(lbl_datosProveedor))
                    .addComponent(lblNombre)
                    .addComponent(txtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_buscar2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panel_cont_icon_user11Layout.setVerticalGroup(
            panel_cont_icon_user11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cont_icon_user11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_icon_user11Layout.createSequentialGroup()
                        .addComponent(lbl_datosProveedor)
                        .addGap(13, 13, 13))
                    .addComponent(lbl_id_Proveedor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_cont_icon_user2Layout = new javax.swing.GroupLayout(panel_cont_icon_user2);
        panel_cont_icon_user2.setLayout(panel_cont_icon_user2Layout);
        panel_cont_icon_user2Layout.setHorizontalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_cont_icon_user8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                                .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panel_cont_icon_user11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panel_cont_icon_user10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont_icon_user6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panel_cont_icon_user7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        panel_cont_icon_user2Layout.setVerticalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_cont_icon_user7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_cont_icon_user11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_cont_icon_user10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_cont_icon_user6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_cont_icon_user8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(panel_cont_icon_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1100, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_entradas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_entradas2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_entradas2MouseClicked

    private void txtidentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidentradaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_buscar1;
    private javax.swing.JLabel lbl_buscar2;
    private javax.swing.JLabel lbl_buscarP;
    private javax.swing.JLabel lbl_datosProveedor;
    private javax.swing.JLabel lbl_delete;
    private javax.swing.JLabel lbl_editar;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_guardar;
    private javax.swing.JLabel lbl_idProducto_1;
    private javax.swing.JLabel lbl_id_Proveedor;
    private javax.swing.JLabel lbl_id_entrada;
    private javax.swing.JLabel lbl_nombreProducto;
    private javax.swing.JLabel lbl_precioEntrada;
    private javax.swing.JLabel lbl_precioVenta;
    private javax.swing.JLabel lbl_saved;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JPanel panel_cont_icon_user1;
    private javax.swing.JPanel panel_cont_icon_user10;
    private javax.swing.JPanel panel_cont_icon_user11;
    private javax.swing.JPanel panel_cont_icon_user2;
    private javax.swing.JPanel panel_cont_icon_user3;
    private javax.swing.JPanel panel_cont_icon_user5;
    private javax.swing.JPanel panel_cont_icon_user6;
    private javax.swing.JPanel panel_cont_icon_user7;
    private javax.swing.JPanel panel_cont_icon_user8;
    private javax.swing.JTable tbl_entradas2;
    private javax.swing.JTextField txtField_fecha;
    private javax.swing.JTextField txtField_precioEntrada;
    private javax.swing.JTextField txtField_precioV;
    private javax.swing.JTextField txtField_stock;
    private javax.swing.JTextField txtTotal1;
    public static javax.swing.JTextField txtidProducto;
    private javax.swing.JTextField txtidentrada;
    public static javax.swing.JTextField txtidproveedor;
    public static javax.swing.JTextField txtnombreProducto;
    public static javax.swing.JTextField txtproveedor;
    // End of variables declaration//GEN-END:variables
}
