/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ControladorProducto;

import style.RoundedPanel;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author rasmx
 */
public class viewRegistroProductos extends javax.swing.JPanel {

    /**
     * Creates new form vistaPrincipal
     */
    
    
    public viewRegistroProductos() {
        this.setBackground(Color.decode("#000511"));
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cont_icon_user1 =  new RoundedPanel(60, new Color(19, 22, 27));
        jLabel10 = new javax.swing.JLabel();
        panel_cont_icon_user2 =  new RoundedPanel(60, new Color(19, 22, 27));
        panel_cont_icon_user3 =  new RoundedPanel(60, Color.WHITE);
        jLabel3 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStockProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodCategoria = new javax.swing.JTextField();
        txtUndMedida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        btnLimpiarProducto = new javax.swing.JButton();
        panel_cont_icon_user5 =  new RoundedPanel(60, Color.WHITE);
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaProductos = new javax.swing.JTable();
        panel_cont_icon_user7 =  new RoundedPanel(60, new Color(0,5,17));
        jLabel11 = new javax.swing.JLabel();
        panel_cont_icon_user8 =  new RoundedPanel(60, new Color(0,5,17));
        btnRegistrarProducto = new javax.swing.JButton();
        panel_cont_icon_user6 =  new RoundedPanel(60, new Color(0, 5, 17));
        jLabel1 = new javax.swing.JLabel();
        btnEditarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(839, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cont_icon_user1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user1.setForeground(new java.awt.Color(19, 22, 27));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registro de Productos");

        javax.swing.GroupLayout panel_cont_icon_user1Layout = new javax.swing.GroupLayout(panel_cont_icon_user1);
        panel_cont_icon_user1.setLayout(panel_cont_icon_user1Layout);
        panel_cont_icon_user1Layout.setHorizontalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_cont_icon_user1Layout.setVerticalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panel_cont_icon_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1100, 60));

        panel_cont_icon_user2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user2.setForeground(new java.awt.Color(19, 22, 27));

        panel_cont_icon_user3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user3.setForeground(new java.awt.Color(19, 22, 27));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel3.setText("ID :");

        txtCodProducto.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel5.setText("Nombre :");

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel6.setText("Stock:");

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel4.setText("ID Categoria:");

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel7.setText("Unidad de Medida:");

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel8.setText("BUSCAR POR ID o NOMBRE:");

        btnLimpiarProducto.setBackground(new java.awt.Color(0, 102, 255));
        btnLimpiarProducto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLimpiarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/iconLimpiar1.png"))); // NOI18N
        btnLimpiarProducto.setText("Limpiar");

        javax.swing.GroupLayout panel_cont_icon_user3Layout = new javax.swing.GroupLayout(panel_cont_icon_user3);
        panel_cont_icon_user3.setLayout(panel_cont_icon_user3Layout);
        panel_cont_icon_user3Layout.setHorizontalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(txtStockProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtUndMedida)
                            .addComponent(txtCodCategoria)
                            .addComponent(txtNombreProducto)
                            .addComponent(txtCodProducto)
                            .addComponent(txtIdBuscar)))
                    .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnLimpiarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cont_icon_user3Layout.setVerticalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUndMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_cont_icon_user5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user5.setForeground(new java.awt.Color(19, 22, 27));

        tblTablaProductos.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        tblTablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTablaProductos.setRowHeight(15);
        tblTablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTablaProductos);

        javax.swing.GroupLayout panel_cont_icon_user5Layout = new javax.swing.GroupLayout(panel_cont_icon_user5);
        panel_cont_icon_user5.setLayout(panel_cont_icon_user5Layout);
        panel_cont_icon_user5Layout.setHorizontalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        panel_cont_icon_user5Layout.setVerticalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_cont_icon_user7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user7.setForeground(new java.awt.Color(19, 22, 27));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Complete la informacion de los productos");

        javax.swing.GroupLayout panel_cont_icon_user7Layout = new javax.swing.GroupLayout(panel_cont_icon_user7);
        panel_cont_icon_user7.setLayout(panel_cont_icon_user7Layout);
        panel_cont_icon_user7Layout.setHorizontalGroup(
            panel_cont_icon_user7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_cont_icon_user7Layout.setVerticalGroup(
            panel_cont_icon_user7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_cont_icon_user8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user8.setForeground(new java.awt.Color(19, 22, 27));

        btnRegistrarProducto.setBackground(new java.awt.Color(0, 102, 255));
        btnRegistrarProducto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRegistrarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/iconGuardar1.png"))); // NOI18N
        btnRegistrarProducto.setText("Guardar");

        javax.swing.GroupLayout panel_cont_icon_user8Layout = new javax.swing.GroupLayout(panel_cont_icon_user8);
        panel_cont_icon_user8.setLayout(panel_cont_icon_user8Layout);
        panel_cont_icon_user8Layout.setHorizontalGroup(
            panel_cont_icon_user8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panel_cont_icon_user8Layout.setVerticalGroup(
            panel_cont_icon_user8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user8Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_cont_icon_user6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user6.setForeground(new java.awt.Color(19, 22, 27));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-saved.png"))); // NOI18N

        btnEditarProducto.setBackground(new java.awt.Color(0, 102, 255));
        btnEditarProducto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/iconEditar1.png"))); // NOI18N
        btnEditarProducto.setText("Editar");

        btnEliminarProducto.setBackground(new java.awt.Color(0, 102, 255));
        btnEliminarProducto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-delete.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");

        btnBuscarProducto.setBackground(new java.awt.Color(0, 102, 255));
        btnBuscarProducto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnBuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/iconBuscar1.png"))); // NOI18N
        btnBuscarProducto.setText("Buscar");

        javax.swing.GroupLayout panel_cont_icon_user6Layout = new javax.swing.GroupLayout(panel_cont_icon_user6);
        panel_cont_icon_user6.setLayout(panel_cont_icon_user6Layout);
        panel_cont_icon_user6Layout.setHorizontalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118)
                .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        panel_cont_icon_user6Layout.setVerticalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_cont_icon_user2Layout = new javax.swing.GroupLayout(panel_cont_icon_user2);
        panel_cont_icon_user2.setLayout(panel_cont_icon_user2Layout);
        panel_cont_icon_user2Layout.setHorizontalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                        .addComponent(panel_cont_icon_user7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_cont_icon_user8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(panel_cont_icon_user6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        panel_cont_icon_user2Layout.setVerticalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_cont_icon_user7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                        .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_cont_icon_user8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_cont_icon_user6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        add(panel_cont_icon_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1100, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void tblTablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaProductosMouseClicked

    }//GEN-LAST:event_tblTablaProductosMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnLimpiarProducto;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_cont_icon_user1;
    private javax.swing.JPanel panel_cont_icon_user2;
    private javax.swing.JPanel panel_cont_icon_user3;
    private javax.swing.JPanel panel_cont_icon_user5;
    private javax.swing.JPanel panel_cont_icon_user6;
    private javax.swing.JPanel panel_cont_icon_user7;
    private javax.swing.JPanel panel_cont_icon_user8;
    private javax.swing.JTable tblTablaProductos;
    private javax.swing.JTextField txtCodCategoria;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtStockProducto;
    private javax.swing.JTextField txtUndMedida;
    // End of variables declaration//GEN-END:variables
    //getter 
    public JButton getBtnBuscarProducto() {
        return btnBuscarProducto;
    }

    public JButton getBtnEditarProducto() {
        return btnEditarProducto;
    }

    public JButton getBtnEliminarProducto() {
        return btnEliminarProducto;
    }

    public JButton getBtnLimpiarProducto() {
        return btnLimpiarProducto;
    }

    public JButton getBtnRegistrarProducto() {
        return btnRegistrarProducto;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JPanel getPanel_cont_icon_user1() {
        return panel_cont_icon_user1;
    }

    public JPanel getPanel_cont_icon_user2() {
        return panel_cont_icon_user2;
    }

    public JPanel getPanel_cont_icon_user3() {
        return panel_cont_icon_user3;
    }

    public JPanel getPanel_cont_icon_user5() {
        return panel_cont_icon_user5;
    }

    public JPanel getPanel_cont_icon_user6() {
        return panel_cont_icon_user6;
    }

    public JPanel getPanel_cont_icon_user7() {
        return panel_cont_icon_user7;
    }

    public JPanel getPanel_cont_icon_user8() {
        return panel_cont_icon_user8;
    }

    public JTable getTblTablaProductos() {
        return tblTablaProductos;
    }

    public JTextField getTxtCodCategoria() {
        return txtCodCategoria;
    }

    public JTextField getTxtCodProducto() {
        return txtCodProducto;
    }

    public JTextField getTxtNombreProducto() {
        return txtNombreProducto;
    }

    public JTextField getTxtStockProducto() {
        return txtStockProducto;
    }

    public JTextField getTxtUndMedida() {
        return txtUndMedida;
    }

    public JTextField getTxtIdBuscar() {
        return txtIdBuscar;
    }


}
