/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ControllerUsuario;
import dto.DTOUsuario;
import style.RoundedPanel;
import java.awt.Color;
import java.util.List;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rasmx
 */
public class ViewRegistroUsuario extends javax.swing.JPanel {

    private DefaultTableModel modeloTabla;
    List<DTOUsuario> usuarios;

    /**
     * Creates new form vistaPrincipal
     */
    public ViewRegistroUsuario() {
        this.setBackground(Color.decode("#000511"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cont_icon_user1 =  new RoundedPanel(60, new Color(19, 22, 27));
        jLabel14 = new javax.swing.JLabel();
        panel_cont_icon_user2 =  new RoundedPanel(60, new Color(19, 22, 27));
        panel_cont_icon_user3 =  new RoundedPanel(60, Color.WHITE);
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        lbl_btn_saved = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_cont_icon_user4 =  new RoundedPanel(60, new Color(19, 22, 27));
        panel_cont_icon_user5 =  new RoundedPanel(60, Color.WHITE);
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        panel_cont_icon_user6 =  new RoundedPanel(60, new Color(19, 22, 27));
        lbl_editar = new javax.swing.JLabel();
        lbl_delete = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(839, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cont_icon_user1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user1.setForeground(new java.awt.Color(19, 22, 27));

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 0, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Registro de Usuarios");

        javax.swing.GroupLayout panel_cont_icon_user1Layout = new javax.swing.GroupLayout(panel_cont_icon_user1);
        panel_cont_icon_user1.setLayout(panel_cont_icon_user1Layout);
        panel_cont_icon_user1Layout.setHorizontalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panel_cont_icon_user1Layout.setVerticalGroup(
            panel_cont_icon_user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panel_cont_icon_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1100, 60));

        panel_cont_icon_user2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user2.setForeground(new java.awt.Color(19, 22, 27));

        panel_cont_icon_user3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user3.setForeground(new java.awt.Color(19, 22, 27));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel5.setText("Apellido");

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel6.setText("Documento");

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel7.setText("Direccion");

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel8.setText("Telefono");

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel9.setText("Correo");

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel10.setText("Tipo Usuario");

        cmbTipoUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor", "Almacenero", "Empleado" }));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel11.setText("Usuario");

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel12.setText("Password");

        javax.swing.GroupLayout panel_cont_icon_user3Layout = new javax.swing.GroupLayout(panel_cont_icon_user3);
        panel_cont_icon_user3.setLayout(panel_cont_icon_user3Layout);
        panel_cont_icon_user3Layout.setHorizontalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                        .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdireccion)
                                .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdocumento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, 203, Short.MAX_VALUE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(txtpass, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panel_cont_icon_user3Layout.setVerticalGroup(
            panel_cont_icon_user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lbl_btn_saved.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-guardar.png"))); // NOI18N
        lbl_btn_saved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_savedMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Complete la informacion del Usuario :");

        javax.swing.GroupLayout panel_cont_icon_user2Layout = new javax.swing.GroupLayout(panel_cont_icon_user2);
        panel_cont_icon_user2.setLayout(panel_cont_icon_user2Layout);
        panel_cont_icon_user2Layout.setHorizontalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lbl_btn_saved)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user2Layout.createSequentialGroup()
                        .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        panel_cont_icon_user2Layout.setVerticalGroup(
            panel_cont_icon_user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_cont_icon_user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_btn_saved)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(panel_cont_icon_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 590));

        panel_cont_icon_user4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user4.setForeground(new java.awt.Color(19, 22, 27));

        panel_cont_icon_user5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user5.setForeground(new java.awt.Color(19, 22, 27));

        tablaUsuarios.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Documento", "Direccion", "Telefono", "Correo", "TipoUser", "Usuario", "Password"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout panel_cont_icon_user5Layout = new javax.swing.GroupLayout(panel_cont_icon_user5);
        panel_cont_icon_user5.setLayout(panel_cont_icon_user5Layout);
        panel_cont_icon_user5Layout.setHorizontalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_cont_icon_user5Layout.setVerticalGroup(
            panel_cont_icon_user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_cont_icon_user4Layout = new javax.swing.GroupLayout(panel_cont_icon_user4);
        panel_cont_icon_user4.setLayout(panel_cont_icon_user4Layout);
        panel_cont_icon_user4Layout.setHorizontalGroup(
            panel_cont_icon_user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panel_cont_icon_user4Layout.setVerticalGroup(
            panel_cont_icon_user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cont_icon_user4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(panel_cont_icon_user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        add(panel_cont_icon_user4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 830, 510));

        panel_cont_icon_user6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cont_icon_user6.setForeground(new java.awt.Color(19, 22, 27));

        lbl_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-editar.png"))); // NOI18N
        lbl_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_editarMouseClicked(evt);
            }
        });

        lbl_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-eliminar.png"))); // NOI18N
        lbl_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_deleteMouseClicked(evt);
            }
        });

        lbl_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/icons-registro/icon-buscar.png"))); // NOI18N
        lbl_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_buscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_cont_icon_user6Layout = new javax.swing.GroupLayout(panel_cont_icon_user6);
        panel_cont_icon_user6.setLayout(panel_cont_icon_user6Layout);
        panel_cont_icon_user6Layout.setHorizontalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lbl_editar)
                .addGap(133, 133, 133)
                .addComponent(lbl_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(lbl_buscar)
                .addGap(104, 104, 104))
        );
        panel_cont_icon_user6Layout.setVerticalGroup(
            panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cont_icon_user6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_cont_icon_user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_buscar)
                    .addComponent(lbl_delete)
                    .addComponent(lbl_editar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(panel_cont_icon_user6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 830, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void lbl_btn_savedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_savedMouseClicked
        try {
            ControllerUsuario controllerUser = new ControllerUsuario();

            int idTipoUsuario = 0;
            String nombre, apellido, documento, direccion, telefono, correo, username, password;

            nombre = txtnombre.getText().trim();
            apellido = txtapellido.getText().trim();
            documento = txtdocumento.getText().trim();
            direccion = txtdireccion.getText().trim();
            telefono = txttelefono.getText().trim();
            correo = txtcorreo.getText().trim();
            if (cmbTipoUsuario.getSelectedItem().equals("Administrador")) {
                idTipoUsuario = 1;
            } else if (cmbTipoUsuario.getSelectedItem().equals("Empleado")) {
                idTipoUsuario = 2;
            }
            username = txtusuario.getText().trim();
            password = txtpass.getText().trim();

            boolean registrado = controllerUser.registrarUsuario(nombre, apellido, documento, direccion, telefono, correo, idTipoUsuario, username, password);

            if (registrado) {
                JOptionPane.showMessageDialog(null, "Registro exitoso");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar el usuario.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_lbl_btn_savedMouseClicked

    private void lbl_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buscarMouseClicked
        try {
            ControllerUsuario controllerUser = new ControllerUsuario();
            String nombre = txtnombre.getText().trim();
            String apellido = txtapellido.getText().trim();
            String documento = txtdocumento.getText().trim();
            String correo = txtcorreo.getText().trim();

            List<DTOUsuario> usuarios = controllerUser.buscarUsuarioPorCriterios(nombre, apellido, documento, correo);

            if (!usuarios.isEmpty()) {
                mostrarUsuariosPorCriterios(usuarios);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron usuarios con esos criterios.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lbl_buscarMouseClicked

    private void lbl_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_deleteMouseClicked
        try {
            String documento = txtdocumento.getText().trim();  // Asumiendo que eliminas por documento
            ControllerUsuario controllerUser = new ControllerUsuario();

            boolean usuarioEliminado = controllerUser.eliminarUsuarioPorDocumento(documento);

            if (usuarioEliminado) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente.");
                limpiarCampos();
                mostrarActualizarTabla();

            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar el usuario.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }    }//GEN-LAST:event_lbl_deleteMouseClicked

    private void lbl_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_editarMouseClicked
        try {
            ControllerUsuario controllerUser = new ControllerUsuario();

            int idTipoUsuario;

            String nombre, apellido, documento, direccion, telefono, correo, username, password;
            nombre = txtnombre.getText().trim();
            apellido = txtapellido.getText().trim();
            documento = txtdocumento.getText().trim();  // Documento que no se puede cambiar
            direccion = txtdireccion.getText().trim();
            telefono = txttelefono.getText().trim();
            correo = txtcorreo.getText().trim();

            if (cmbTipoUsuario.getSelectedItem().equals("Administrador")) {
                idTipoUsuario = 1;
            } else {
                idTipoUsuario = 2;
            }
            username = txtusuario.getText().trim();
            password = txtpass.getText().trim();
            DefaultTableModel tablaModel = (DefaultTableModel) tablaUsuarios.getModel();

            boolean usuarioeditado = controllerUser.editarUsuario(nombre, apellido, documento, direccion, telefono, correo, idTipoUsuario, username, password);

            if (usuarioeditado) {
                JOptionPane.showMessageDialog(null, "Usuario actualizado exitosamente.");
                mostrarActualizarTabla();

            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el usuario.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lbl_editarMouseClicked

    private void limpiarCampos() {
        int idTipoUsuario = 0;
        String nombre, apellido, documento, direccion, telefono, correo, username, password;

        txtnombre.setText("");
        txtapellido.setText("");
        txtdocumento.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");

        if (cmbTipoUsuario.getSelectedItem().equals("Administrador")) {
            idTipoUsuario = 1;
        } else if (cmbTipoUsuario.getSelectedItem().equals("Empleado")) {
            idTipoUsuario = 2;
        }

        txtusuario.setText("");
        txtpass.setText("");
    }

    private DefaultTableModel construirModeloTabla(List<DTOUsuario> usuarios) {
        String[] columnas = {"ID", "Nombre", "Apellido", "Documento", "Dirección", "Teléfono", "Correo", "Tipo Usuario", "Usuario", "Contraseña"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        for (DTOUsuario usuario : usuarios) {
            Object[] fila = new Object[10];
            fila[0] = usuario.getIdUsuario();
            fila[1] = usuario.getNombre();
            fila[2] = usuario.getApellido();
            fila[3] = usuario.getDocumento();
            fila[4] = usuario.getDireccion();
            fila[5] = usuario.getTelefono();
            fila[6] = usuario.getCorreo();
            fila[7] = usuario.getIdTipoUsuario() == 1 ? "Administrador" : "Empleado"; // Puedes convertir el tipo de usuario a texto
            fila[8] = usuario.getUsername();
            fila[9] = usuario.getPassword();
            modelo.addRow(fila);
        }

        return modelo;
    }

    private void mostrarUsuariosPorCriterios(List<DTOUsuario> usuarios) {
        this.usuarios = usuarios;
        modeloTabla = construirModeloTabla(usuarios);
        tablaUsuarios.setModel(modeloTabla);
    }

    private void mostrarActualizarTabla() {
        try {
            ControllerUsuario controlleruser = new ControllerUsuario();
            List<DTOUsuario> usuarios = controlleruser.obtenerUsuarios();
            DefaultTableModel modelo = construirModeloTabla(usuarios);
            tablaUsuarios.setModel(modelo);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_btn_saved;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_delete;
    private javax.swing.JLabel lbl_editar;
    private javax.swing.JPanel panel_cont_icon_user1;
    private javax.swing.JPanel panel_cont_icon_user2;
    private javax.swing.JPanel panel_cont_icon_user3;
    private javax.swing.JPanel panel_cont_icon_user4;
    private javax.swing.JPanel panel_cont_icon_user5;
    private javax.swing.JPanel panel_cont_icon_user6;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}